/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.io.BufferedWriter;
import java.io.Writer;
import java.io.OutputStreamWriter;
import java.io.FileOutputStream;
import java.io.IOException;


public
class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected Ebnf parser;

  // added
  public String valor;

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(Ebnf p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

     public String toString() { return EbnfTreeConstants.jjtNodeName[id]; }
     public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
  out its children. */

  public void dump(String prefix, Writer writer) throws IOException{
    System.out.println(toString(prefix));

    dump2(prefix +" ");

    for (int i = 0; i < children.length; i++) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.printNode(writer);
        }
      }
  }

  public void dump2(String prefix) {
    System.out.println(toString(prefix));

    if(children == null)
      System.out.println(prefix+" ["+this.value+"]");

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
           n.dump2(prefix +" ");
        }
      }
    }
  }


  public void printRule(Writer writer) throws IOException {
    if(children == null) {
      System.out.println("ERROR");
      System.exit(1);
    }
    SimpleNode n0 = (SimpleNode) children[0];
    writer.write("< "+n0.jjtGetValue()+" : ");
    SimpleNode n = (SimpleNode)children[1];
    n.printNode(writer);
    writer.write(" >");
  }

public void printSequence(Writer writer) throws IOException {
  for (int i = 0; i < children.length; i++) {
    SimpleNode ni = (SimpleNode) children[i];
    //System.out.println("teste:"+ni.value);
    ni.printNode(writer);
    if(this.value != null && i < children.length-1 )
    {
      //System.out.println("teste/:"+ni.value);
      if(this.value.equals("|"))
      {
        writer.write(" | ");
      }
      else
        if(this.value.equals(","))
          writer.write(" ");
    }
}
}

  public void printRepetition(Writer writer) throws IOException {
    writer.write(" ( ");

    for (int i = 0; i < children.length; i++) {
      SimpleNode ni = (SimpleNode) children[i];
      ni.printNode(writer);

    }
    writer.write(" )* ");

  }
  public void printGrouping(Writer writer) throws IOException {
    writer.write(" ( ");

    for (int i = 0; i < children.length; i++) {
      SimpleNode ni = (SimpleNode) children[i];
      ni.printNode(writer);

    }
    writer.write(" ) ");
  }
  public void printOptional(Writer writer) throws IOException {
    writer.write(" [ ");

    for (int i = 0; i < children.length; i++) {
      SimpleNode ni = (SimpleNode) children[i];
      ni.printNode(writer);

    }
    writer.write(" ] ");
  }

  public void printNode(Writer writer) throws IOException {
      
    switch(this.id)
    {
      case EbnfTreeConstants.JJTRULE :
        printRule(writer);
        writer.write("\n");
        break;
      case EbnfTreeConstants.JJTSEQUENCE :
        printSequence(writer);
        break;
      case EbnfTreeConstants.JJTREPETITION :
        printRepetition(writer);
        break;
      case EbnfTreeConstants.JJTIDENTIFIER :
        writer.write(this.jjtGetValue()+" ");
        break;
      case EbnfTreeConstants.JJTTERMINAL :    
        writer.write(this.jjtGetValue()+" ");
        break;
      case EbnfTreeConstants.JJTGROUPING :
        printGrouping(writer);
        break;
      case EbnfTreeConstants.JJTOPTION :
        printOptional(writer);
        break;
      case EbnfTreeConstants.JJTSPECIALSEQ :
        writer.write(this.jjtGetValue()+" ");
        break;
      default :   
        System.out.println("Não processado: "+EbnfTreeConstants.jjtNodeName[this.id]);
        break;
    }

  }
}

/* JavaCC - OriginalChecksum=2edd50316e282230d4638a37fa816c17 (do not edit this line) */
